version: '3.8'

x-shared_environment: &shared_environment
  FOLDER_LIBSO: ${FOLDER_LIBSO}
  TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  MONGO_HOST: ${MONGO_HOST}
  MONGO_PORT: ${MONGO_PORT}
  MONGO_DB: ${MONGO_DB}
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}
  XH_SUPER_USER: ${XH_SUPER_USER}
  XH_SUPER_PWD: ${XH_SUPER_PWD}

services:
  xhpigmod-v2-server:
    image: xhpigmod-v2-server
    environment:
      <<: *shared_environment
    volumes:
      - "${FOLDER_LIBSO_HOST}:${FOLDER_LIBSO}"
    networks:
      - all

  xhpigmod-v2-cloudflare:
    image: cloudflare/cloudflared
    command: tunnel --protocol http2 --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOTQ0NDM0YjgzY2JmM2YxMGE1NjQ2MGIxZGRmYjViYjEiLCJ0IjoiNzI0YWZiMjItNGU0Mi00NGYwLWE2MGEtMzRhMjMzN2IwZjIwIiwicyI6IlpHWTNNRGcxWTJFdE56Um1aUzAwWWpNNUxUZzNZV0l0WmpkaU1EbGxOREV3T0RCbSJ9
    networks:
      - all

  xhpigmod-v2-mongo:
    image: mongo:7.0.3
    command: mongod --quiet --logpath /dev/null
    environment:
      <<: *shared_environment
    ports:
      - "127.0.0.1:27027:27017"
    volumes:
      - ./conf/dev/mongod.conf:/etc/mongodb.conf
      - ./data/mongo/log:/var/log/mongodb/
      - ./data/mongo/data:/data/db
    networks:
      - all

  xhpigmod-v2-redis:
    image: redis:7.2.3-alpine3.18
    environment:
      <<: *shared_environment
    ports:
      - "127.0.0.1:6389:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/dev/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    networks:
      - all

networks:
  all: