export const QUEUE_HDR_ADS_REWARD = 'HDR_ADS_REWARD';
export const QUEUE_ACCOUNT_ACTIVE = 'ACCOUNT_ACTIVE';

export const JOB_ACCOUNT_ACTIVE_HDR = 'ACCOUNT_ACTIVE_HDR';

export const JOB_HDR_ADS_REWARD_PREFIX_ADS1 = 'ads1_';
export const JOB_HDR_ADS_REWARD_PREFIX_ADS2 = 'ads2_';
